name: pip_services_attachments
version: "1.0.0"
description: Blob Attachments microservice for Pip.Services in Dart. It records all documents that attached to a particilar blob.
homepage: https://github.com/pip-services-content/pip-services-attachments-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pip_services3_commons: ^1.0.9
  pip_services3_components: ^1.0.6
  pip_services3_container: ">=1.0.3 <2.0.0"
  pip_services3_rpc: ^1.0.3
  pip_services3_data: ^1.0.6
  pip_services3_mongodb: ^1.0.4
  #pip_clients_blobs: ^1.0.0
  http: "^0.12.0"
  angel_framework: ^2.1.1
  mongo_dart_query: "^0.4.1"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'

